### ISSUE TITLE
Consider making -o the default behavior

### ISSUE THREAD

**Issue by dimitryvolkov** [idobh2/node-gitcheckout-cli#2]
It seems that most often then not, I'm checking out remote branches, it would be nice to have -o be the default option.

Maybe have the behavior be that if there's already a local branch tracking the remote one, it would "shadow" the remote branch in the list to prevent duplicate entries.

**Comment by idobh2** [comment]
Absolutely agree. Changed it in 1.0.4 (commit 74f273c655ae5eb7360623b482a619822b7a34e6)
`gitcheckout` will list origin and local branches
`gitcheckout -l` will only list local branches
